theme: jekyll-theme-architect
show_downloads: false
title: میکرو فرانت‌اند
description: گسترش ایده میکروسرویس به فرانت‌اند و توسعه سمت کاربر
lang: fa
dir: rtl
github:
  is_project_page: true
  repository_url: https://github.com/johnadib/micro-frontends
exclude:
  - 2-composition-universal
  - 3-data-fetching
  - node_modules
